version: "3.9"

services:
  servidor:
    build: ./servidor
    container_name: servidor
    ports:
      - "5000:5000"
    networks:
      - red_app

  cliente:
    build: ./cliente
    container_name: cliente
    environment:
      - SERVIDOR_URL=http://servidor:5000
    depends_on:
      - servidor
    networks:
      - red_app

networks:
  red_app:
    driver: bridge
